"""ABIF (AB1) binary file writer.

Writes tags compatible with AB1 viewers (SnapGene, Chromas, FinchTV, ApE).
Tag structure matches hyraxAbif output for maximum compatibility:
  DATA9-12  — 4 trace channels (int16 big-endian, GATC order)
  PBAS1     — base calls (ASCII)
  PLOC1     — peak positions (uint16 big-endian)
  PCON2     — quality/confidence values
  FWO_1     — channel order "GATC"
  LANE1     — lane number
  PDMF1/2   — mobility file name
  S/N%1     — signal-to-noise ratios
  SMPL1     — sample name
  CMNT1     — comment
"""

import struct
import numpy as np

# ABIF constants
ABIF_MAGIC = b"ABIF"
ABIF_VERSION = 101  # version 1.01

# Element type codes
ELEM_BYTE = 1       # uint8
ELEM_CHAR = 2       # char (ASCII)
ELEM_SHORT = 4      # int16
ELEM_LONG = 5       # int32
ELEM_PSTRING = 18   # pascal string
ELEM_CSTRING = 19   # c string

# Directory entry size
DIR_ENTRY_SIZE = 28


def _pad4(n):
    """Round up to next multiple of 4."""
    return (n + 3) & ~3


def write_ab1(filename, traces, base_calls, peak_positions, sample_name="Sample",
              quality_scores=None):
    """Write an AB1 file compatible with SnapGene, Chromas, FinchTV, and ApE.

    Args:
        filename: output .ab1 path
        traces: dict with "A","C","G","T" keys → numpy int16 arrays
        base_calls: string of base calls
        peak_positions: list/array of peak positions (int)
        sample_name: sample name string
        quality_scores: list of int quality values (0-60), or None for default 40
    """
    # Prepare all data items: (tag_name_bytes, tag_number, elem_type, elem_size, num_elements, data_bytes)
    items = []

    # DATA9-12: trace channels in GATC order (standard AB1 channel mapping)
    # DATA9=G, DATA10=A, DATA11=T, DATA12=C
    channel_map = [("G", 9), ("A", 10), ("T", 11), ("C", 12)]
    for base, data_num in channel_map:
        arr = traces[base].astype(">i2")  # big-endian int16
        items.append((b"DATA", data_num, ELEM_SHORT, 2, len(arr), arr.tobytes()))

    # FWO_1: channel order string "GATC" (inline, 4 bytes)
    items.append((b"FWO_", 1, ELEM_CHAR, 1, 4, b"GATC"))

    # LANE1: lane number = 1 (inline, 2 bytes)
    items.append((b"LANE", 1, ELEM_SHORT, 2, 1, struct.pack(">h", 1)))

    # PBAS1 + PBAS2: base calls (both tags for maximum compatibility)
    # PBAS1 = original basecalls, PBAS2 = edited basecalls
    # Tracy requires PBAS2; real ABI instruments write both
    calls_bytes = base_calls.encode("ascii")
    items.append((b"PBAS", 1, ELEM_CHAR, 1, len(calls_bytes), calls_bytes))
    items.append((b"PBAS", 2, ELEM_CHAR, 1, len(calls_bytes), calls_bytes))

    # PCON1 + PCON2: quality/confidence values (both tags)
    if quality_scores is None:
        quality_scores = [40] * len(base_calls)
    pcon = bytes(min(q, 255) for q in quality_scores)
    items.append((b"PCON", 1, ELEM_CHAR, 1, len(pcon), pcon))
    items.append((b"PCON", 2, ELEM_CHAR, 1, len(pcon), pcon))

    # PDMF1/2: mobility file name (required by some viewers)
    mob_name = b"KB_3500_POP7_BDTv3.mob"
    pdmf = struct.pack("B", len(mob_name)) + mob_name
    items.append((b"PDMF", 1, ELEM_PSTRING, 1, len(pdmf), pdmf))
    items.append((b"PDMF", 2, ELEM_PSTRING, 1, len(pdmf), pdmf))

    # PLOC1 + PLOC2: peak positions (both tags for Tracy compatibility)
    ploc = np.array(peak_positions, dtype=">u2")  # big-endian uint16
    items.append((b"PLOC", 1, ELEM_SHORT, 2, len(ploc), ploc.tobytes()))
    items.append((b"PLOC", 2, ELEM_SHORT, 2, len(ploc), ploc.tobytes()))

    # S/N%1: signal-to-noise ratios per channel (G, A, T, C)
    # Compute from actual trace data instead of using hardcoded values
    try:
        from ab1tools.signal import compute_snr
        snr = compute_snr(traces)
        sn_values = struct.pack(">4h", snr.get("G", 50), snr.get("A", 70),
                                snr.get("T", 75), snr.get("C", 45))
    except (ImportError, Exception):
        sn_values = struct.pack(">4h", 53, 75, 79, 48)  # fallback
    items.append((b"S/N%", 1, ELEM_SHORT, 2, 4, sn_values))

    # SMPL1: sample name (pascal string)
    name_bytes = sample_name.encode("ascii")[:255]
    pstring = struct.pack("B", len(name_bytes)) + name_bytes
    items.append((b"SMPL", 1, ELEM_PSTRING, 1, len(pstring), pstring))

    # CMNT1: comment
    comment = b"Generated by ab1tools"
    cmnt = struct.pack("B", len(comment)) + comment
    items.append((b"CMNT", 1, ELEM_PSTRING, 1, len(cmnt), cmnt))

    num_entries = len(items)

    # === Layout the file ===
    header_size = 128
    data_start = header_size

    # Calculate data block positions
    data_offsets = []
    current_offset = data_start
    for _, _, _, _, _, data_bytes in items:
        data_offsets.append(current_offset)
        current_offset += _pad4(len(data_bytes))

    dir_offset = current_offset

    # === Write the file ===
    with open(filename, "wb") as f:
        # --- Header (128 bytes) ---
        f.write(ABIF_MAGIC)                        # 0-3: magic number
        f.write(struct.pack(">H", ABIF_VERSION))   # 4-5: version

        # Root directory entry (at offset 6, 28 bytes)
        dir_total_size = num_entries * DIR_ENTRY_SIZE
        f.write(struct.pack(
            ">4sI H H I I I 4s",
            b"tdir",           # tag name
            1,                 # tag number
            1023,              # element type (directory)
            DIR_ENTRY_SIZE,    # element size
            num_entries,       # number of elements
            dir_total_size,    # total data size
            dir_offset,        # offset to directory
            b"\x00" * 4,       # dataHandle (unused)
        ))

        # Pad rest of header to 128 bytes
        f.write(b"\x00" * (header_size - f.tell()))

        # --- Data blocks ---
        for i, (_, _, _, _, _, data_bytes) in enumerate(items):
            assert f.tell() == data_offsets[i], \
                f"Offset mismatch: expected {data_offsets[i]}, got {f.tell()}"
            f.write(data_bytes)
            padding = _pad4(len(data_bytes)) - len(data_bytes)
            if padding:
                f.write(b"\x00" * padding)

        # --- Directory entries ---
        assert f.tell() == dir_offset
        for i, (tag_name, tag_num, elem_type, elem_size, num_elem, data_bytes) in enumerate(items):
            data_size = len(data_bytes)

            # If data fits in 4 bytes, store inline in the offset field
            if data_size <= 4:
                inline_data = data_bytes + b"\x00" * (4 - data_size)
                offset_or_data = struct.unpack(">I", inline_data)[0]
            else:
                offset_or_data = data_offsets[i]

            entry = struct.pack(
                ">4sI H H I I I 4s",
                tag_name,
                tag_num,
                elem_type,
                elem_size,
                num_elem,
                data_size,
                offset_or_data,
                b"\x00" * 4,  # dataHandle (unused)
            )
            f.write(entry)

    return filename
