"""Signal Deconvolution-based Variant Calling (SDVC) from chromatogram traces.

Implements variant detection directly from 4-channel electropherogram signals
using peak deconvolution, dynamic thresholding, and multi-position consistency.

This module operates on AB1 trace data (int16 arrays for A/C/G/T channels)
and identifies positions with mixed-base signals indicating heterozygous or
mosaic variants.

Dual-mode algorithm:
    Mode 1 (Control-free): Detect variants from any AB1 file without control
        1. Extract local peak heights from each channel (±window around peak center)
        2. Subtract baseline (10th percentile of upstream/downstream regions)
        3. Normalize across channels to get per-base frequencies
        4. Apply dynamic threshold (adapts to local noise) to call variants
        5. Score confidence based on minor/major ratio × local SNR
        6. Optionally apply Bayesian prior for known hotspot regions
        7. Enhance calls via multi-position sliding window consistency

    Mode 2 (Control-enhanced): Use matched control trace for higher sensitivity
        0. Subtract scaled control trace from sample to remove systematic baseline
        1-7. Same as Mode 1, but on control-subtracted traces
        LOD improves from ~2-3% to <1%

References:
    - Ewing et al. (1998) Genome Res. 8:175-185 [phred quality scores]
    - DePristo et al. (2011) Nat. Genet. 43:491-498 [Bayesian variant calling]
    - Otsu (1979) IEEE TSMC 9:62-66 [adaptive thresholding, adapted]
    - Brinkman et al. (2014) Nucleic Acids Res. 42:e168 [TIDE, control subtraction]
"""

import math
import numpy as np

BASES = "ACGT"


class VariantCaller:
    """Signal Deconvolution-based Variant Caller (SDVC).

    Detects mixed-base positions from 4-channel chromatogram trace data.
    Works with AB1 files generated by ab1tools or from real Sanger sequencers.

    Parameters
    ----------
    traces : dict
        Mapping of base characters ("A", "C", "G", "T") to numpy arrays
        (int16 or float) of trace intensities.
    peak_positions : list of int
        Trace x-positions of peak centers (from PLOC tag in AB1).
    base_calls : str, optional
        Called bases at each peak position (from PBAS tag in AB1).
        If None, will be inferred from traces.
    min_threshold : float
        Minimum minor allele frequency to consider a variant (default 0.05).
    sensitivity : float
        Dynamic threshold sensitivity parameter k (default 0.5).
        Lower values = more sensitive (more calls), higher = more specific.
    prior : float
        Bayesian prior probability of a variant (default 0.01).
        Set higher (e.g. 0.5) at known mutation hotspots or CRISPR cut sites.
    window_size : int
        Sliding window size for multi-position consistency (default 5).
    peak_window : int
        Half-width for peak signal extraction (default 3 trace points).
    baseline_upstream : int
        Upstream distance for baseline estimation (default 15 trace points).
    baseline_gap : int
        Gap between baseline region and peak (default 5 trace points).
    """

    def __init__(self, traces, peak_positions, base_calls=None,
                 min_threshold=0.05, sensitivity=0.5, prior=0.01,
                 window_size=5, peak_window=3,
                 baseline_upstream=15, baseline_gap=5):
        self.traces = traces
        self.peaks = list(peak_positions)
        self.base_calls = base_calls or ""
        self.min_threshold = min_threshold
        self.sensitivity = sensitivity
        self.prior = prior
        self.window_size = window_size
        self.peak_window = peak_window
        self.baseline_upstream = baseline_upstream
        self.baseline_gap = baseline_gap

        # Precompute trace length
        first_base = next(iter(traces))
        self.trace_len = len(traces[first_base])

        # Compute global noise floor for dynamic thresholding
        self._global_noise = self._compute_global_noise()

    def _compute_global_noise(self):
        """Compute global noise floor as median of inter-peak signal."""
        noise_samples = []
        for i in range(1, min(len(self.peaks), 50)):
            mid = (self.peaks[i - 1] + self.peaks[i]) // 2
            for base in BASES:
                arr = self.traces[base]
                val = float(arr[mid]) if 0 <= mid < self.trace_len else 0.0
                noise_samples.append(abs(val))
        if noise_samples:
            return float(np.median(noise_samples))
        return 1.0

    def _get_peak_signal(self, base, center):
        """Extract peak signal height from a channel at a given position.

        Uses max value within ±peak_window of center to handle slight
        peak position offsets.
        """
        arr = self.traces[base]
        lo = max(0, center - self.peak_window)
        hi = min(self.trace_len, center + self.peak_window + 1)
        if lo >= hi:
            return 0.0
        return float(np.max(arr[lo:hi]))

    def _get_baseline(self, base, center):
        """Estimate baseline for a channel at a given position.

        Uses the minimum of upstream and downstream inter-peak regions
        to avoid bias from neighboring peak signals bleeding into the
        baseline window. Takes the 10th percentile to be robust against
        occasional noise spikes.
        """
        arr = self.traces[base]

        # Upstream baseline
        up_lo = max(0, center - self.baseline_upstream)
        up_hi = max(0, center - self.baseline_gap)
        # Downstream baseline
        dn_lo = min(self.trace_len, center + self.baseline_gap)
        dn_hi = min(self.trace_len, center + self.baseline_upstream)

        segments = []
        if up_hi > up_lo:
            segments.append(arr[up_lo:up_hi].astype(np.float64))
        if dn_hi > dn_lo:
            segments.append(arr[dn_lo:dn_hi].astype(np.float64))

        if not segments:
            return 0.0

        # Use minimum of upstream/downstream 10th percentiles
        # This prevents neighboring peak signals from inflating baseline
        percentiles = [float(np.percentile(s, 10)) for s in segments]
        return min(percentiles)

    def _get_local_snr(self, center):
        """Compute local signal-to-noise ratio around a position.

        SNR = max peak height across channels / std of baseline region.
        """
        peak_heights = []
        baseline_values = []
        for base in BASES:
            peak_heights.append(self._get_peak_signal(base, center))
            arr = self.traces[base]
            lo = max(0, center - self.baseline_upstream)
            hi = max(0, center - self.baseline_gap)
            if hi > lo:
                baseline_values.extend(arr[lo:hi].astype(np.float64).tolist())

        max_peak = max(peak_heights) if peak_heights else 1.0
        baseline_std = float(np.std(baseline_values)) if baseline_values else 1.0
        return max_peak / max(baseline_std, 1.0)

    def _dynamic_threshold(self, center):
        """Compute position-specific variant calling threshold.

        Adapts to local noise floor:
            tau = min_threshold + sensitivity * (noise_floor / max_signal)

        At high-SNR positions: tau ≈ min_threshold (most sensitive)
        At noisy positions with weak signal: tau increases (more conservative)

        The noise floor is estimated from the global inter-peak baseline,
        NOT from signal variance (which would penalize heterozygous positions).
        """
        # Get the dominant signal height at this position
        max_signal = 0.0
        for base in BASES:
            raw = self._get_peak_signal(base, center)
            bl = self._get_baseline(base, center)
            max_signal = max(max_signal, raw - bl)

        if max_signal <= 0:
            return 1.0  # No signal → cannot call anything

        # Use global noise floor relative to local signal strength
        tau = self.min_threshold + self.sensitivity * (self._global_noise / (max_signal + 1e-9))
        return min(tau, 0.5)  # Cap at 50%

    def _apply_bayesian_prior(self, minor_freq, snr):
        """Apply Bayesian prior to variant frequency estimate.

        posterior ∝ likelihood(minor_freq | signal) × prior
        Likelihood modeled as signal strength normalized by SNR.

        Returns adjusted confidence score.
        """
        # Likelihood: higher minor freq and higher SNR → more likely real
        likelihood = minor_freq * min(snr / 10.0, 1.0)
        posterior = likelihood * self.prior
        # Normalize to 0-1 range
        return min(posterior / (posterior + (1 - self.prior) * (1 - likelihood) + 1e-9), 1.0)

    def call_variants(self):
        """Run SDVC algorithm on all peak positions.

        Returns
        -------
        list of dict
            Each dict contains:
            - pos_0based : int — 0-based position index
            - pos_1based : int — 1-based position (for display/output)
            - trace_pos : int — trace x-coordinate of peak center
            - consensus_base : str — called base at this position
            - major_base : str — highest-frequency base
            - major_freq : float — frequency of major base (0-1)
            - minor_base : str — second-highest-frequency base
            - minor_freq : float — frequency of minor base (0-1)
            - third_base : str — third-highest-frequency base
            - third_freq : float — frequency of third base (0-1)
            - freq_A, freq_C, freq_G, freq_T : float — per-base frequencies
            - is_variant : bool — whether position passes threshold
            - confidence : float — variant call confidence (0-1)
            - snr : float — local signal-to-noise ratio
            - threshold : float — dynamic threshold used at this position
        """
        results = []

        for i, pos in enumerate(self.peaks):
            # Step 1: Extract peak signals with baseline correction
            signals = {}
            for base in BASES:
                raw = self._get_peak_signal(base, pos)
                bl = self._get_baseline(base, pos)
                signals[base] = max(raw - bl, 0.0)

            total = sum(signals.values())
            if total == 0:
                # No signal at this position
                results.append(self._make_empty_result(i, pos))
                continue

            # Step 2: Cross-channel normalization to frequencies
            freq = {base: signals[base] / total for base in BASES}

            # Step 3: Rank bases by frequency
            sorted_bases = sorted(BASES, key=lambda b: freq[b], reverse=True)
            major = sorted_bases[0]
            minor = sorted_bases[1]
            third = sorted_bases[2]

            # Step 4: Dynamic threshold
            tau = self._dynamic_threshold(pos)

            # Step 5: Call variant
            is_variant = freq[minor] >= tau

            # Step 6: Local SNR
            snr = self._get_local_snr(pos)

            # Step 7: Confidence score
            # Base confidence: minor/major ratio weighted by SNR
            if freq[major] > 0:
                raw_confidence = (freq[minor] / freq[major]) * min(snr / 20.0, 1.0)
            else:
                raw_confidence = 0.0

            # Apply Bayesian prior if enabled (prior > 0)
            if self.prior > 0 and is_variant:
                bayesian_score = self._apply_bayesian_prior(freq[minor], snr)
                confidence = 0.7 * raw_confidence + 0.3 * bayesian_score
            else:
                confidence = raw_confidence

            confidence = min(confidence, 1.0)

            # Consensus base (from base_calls if available, else major)
            con_base = self.base_calls[i] if i < len(self.base_calls) else major

            results.append({
                "pos_0based": i,
                "pos_1based": i + 1,
                "trace_pos": pos,
                "consensus_base": con_base,
                "major_base": major,
                "major_freq": round(freq[major], 4),
                "minor_base": minor,
                "minor_freq": round(freq[minor], 4),
                "third_base": third,
                "third_freq": round(freq[third], 4),
                "freq_A": round(freq.get("A", 0.0), 4),
                "freq_C": round(freq.get("C", 0.0), 4),
                "freq_G": round(freq.get("G", 0.0), 4),
                "freq_T": round(freq.get("T", 0.0), 4),
                "is_variant": is_variant,
                "confidence": round(confidence, 4),
                "snr": round(snr, 2),
                "threshold": round(tau, 4),
            })

        # Step 8: Multi-position consistency enhancement
        self._apply_multiposition_consistency(results)

        return results

    def _apply_multiposition_consistency(self, results):
        """Enhance or suppress variant calls based on neighboring positions.

        - If ≥2 neighbors within window are also variants → boost confidence ×1.2
        - If isolated single-position variant with low confidence → flag as suspect
        - True biological variants (from clonal populations) tend to be isolated
          but have high confidence; noise-induced calls cluster or are low-confidence

        This is adapted from the local context approach in GATK HaplotypeCaller
        (DePristo et al., 2011).
        """
        n = len(results)
        half = self.window_size // 2

        for i in range(n):
            if not results[i]["is_variant"]:
                continue

            # Count variant neighbors within window
            neighbor_variants = 0
            for j in range(max(0, i - half), min(n, i + half + 1)):
                if j != i and results[j]["is_variant"]:
                    neighbor_variants += 1

            # Boost confidence if neighbors are also variant
            # (indicates a real heterozygous region, not random noise)
            if neighbor_variants >= 2:
                results[i]["confidence"] = min(
                    results[i]["confidence"] * 1.2, 1.0
                )
            # Flag isolated low-confidence calls as suspect
            elif neighbor_variants == 0 and results[i]["confidence"] < 0.3:
                results[i]["confidence"] *= 0.5

    def _make_empty_result(self, idx, trace_pos):
        """Create a result dict for a position with no signal."""
        con_base = self.base_calls[idx] if idx < len(self.base_calls) else "N"
        return {
            "pos_0based": idx,
            "pos_1based": idx + 1,
            "trace_pos": trace_pos,
            "consensus_base": con_base,
            "major_base": "N",
            "major_freq": 0.0,
            "minor_base": "N",
            "minor_freq": 0.0,
            "third_base": "N",
            "third_freq": 0.0,
            "freq_A": 0.0, "freq_C": 0.0, "freq_G": 0.0, "freq_T": 0.0,
            "is_variant": False,
            "confidence": 0.0,
            "snr": 0.0,
            "threshold": 1.0,
        }

    def get_variants(self):
        """Convenience method: call variants and return only variant positions.

        Returns
        -------
        list of dict
            Only positions where is_variant is True.
        """
        return [r for r in self.call_variants() if r["is_variant"]]


class IndelDetector:
    """Detect insertions and deletions from chromatogram trace data.

    Indels in heterozygous samples cause the two alleles to become out
    of phase downstream of the indel site. This manifests as:
    - Sudden increase in "aberrant" (non-dominant) signal after the break point
    - The downstream signal is a superposition of two shifted traces

    The algorithm:
    1. Compute per-position aberrant signal fraction (non-dominant channels)
    2. Identify the break point where aberrant fraction suddenly increases
    3. Estimate indel size by testing different shift offsets
    4. Score each candidate indel by signal coherence after deconvolution

    This approach is inspired by TIDE (Brinkman et al., 2014) but operates
    without a control trace by using the upstream region as self-reference.

    Parameters
    ----------
    traces : dict
        Trace data {"A","C","G","T" → numpy arrays}.
    peak_positions : list of int
        Peak center positions.
    base_calls : str
        Called base sequence.
    max_indel_size : int
        Maximum indel size to test (default 20).
    aberrant_threshold : float
        Minimum aberrant signal fraction to consider a break point (default 0.15).
    """

    def __init__(self, traces, peak_positions, base_calls,
                 max_indel_size=20, aberrant_threshold=0.15):
        self.traces = traces
        self.peaks = list(peak_positions)
        self.base_calls = base_calls
        self.max_indel = max_indel_size
        self.aberrant_threshold = aberrant_threshold
        self.n_bases = len(base_calls)

        first_base = next(iter(traces))
        self.trace_len = len(traces[first_base])

    def _get_peak_signal(self, base, center, window=3):
        arr = self.traces[base]
        lo = max(0, center - window)
        hi = min(self.trace_len, center + window + 1)
        if lo >= hi:
            return 0.0
        return float(np.max(arr[lo:hi]))

    def _aberrant_fraction(self, pos_idx):
        """Compute fraction of signal NOT from the dominant base at position."""
        if pos_idx >= len(self.peaks):
            return 0.0
        center = self.peaks[pos_idx]
        signals = {}
        for base in BASES:
            signals[base] = self._get_peak_signal(base, center)
        total = sum(signals.values())
        if total == 0:
            return 0.0
        dominant = max(signals.values())
        return 1.0 - (dominant / total)

    def detect_indels(self):
        """Detect insertions and deletions from trace signal patterns.

        Returns
        -------
        list of dict
            Each detected indel contains:
            - break_pos : int — position where indel starts (0-based)
            - indel_size : int — negative for deletion, positive for insertion
            - aberrant_before : float — mean aberrant fraction before break
            - aberrant_after : float — mean aberrant fraction after break
            - confidence : float — detection confidence (0-1)
            - type : str — "deletion" or "insertion"
        """
        if self.n_bases < 50:
            return []  # too short for reliable indel detection

        # Step 1: Compute aberrant signal fraction at each position
        aberrant = np.array([self._aberrant_fraction(i) for i in range(self.n_bases)])

        # Step 2: Find break point(s) — position where aberrant signal jumps
        # Use a sliding window to find the maximum change point
        window = 10
        candidates = []

        for i in range(window, self.n_bases - window):
            before = np.mean(aberrant[max(0, i-window):i])
            after = np.mean(aberrant[i:min(self.n_bases, i+window)])
            delta = after - before

            if delta > self.aberrant_threshold and after > 0.2:
                candidates.append({
                    'pos': i,
                    'delta': delta,
                    'before': before,
                    'after': after,
                })

        if not candidates:
            return []

        # Step 3: Merge nearby candidates (keep the one with highest delta)
        merged = []
        candidates.sort(key=lambda x: -x['delta'])
        used = set()
        for c in candidates:
            if any(abs(c['pos'] - u) < window for u in used):
                continue
            merged.append(c)
            used.add(c['pos'])

        # Step 4: For each break point, estimate indel size
        results = []
        for bp in merged:
            pos = bp['pos']

            # Try different indel sizes and score by downstream coherence
            best_size = 0
            best_score = 0

            # Get spacing between peaks
            if len(self.peaks) > 1:
                spacing = self.peaks[1] - self.peaks[0]
            else:
                spacing = 10

            for size in range(-self.max_indel, self.max_indel + 1):
                if size == 0:
                    continue

                # Score: how well does shifting the downstream trace by 'size'
                # positions improve signal coherence?
                score = 0
                n_scored = 0

                for j in range(pos + 5, min(pos + 30, self.n_bases)):
                    if j >= len(self.peaks):
                        break

                    center = self.peaks[j]
                    # Original dominant signal
                    called = self.base_calls[j] if j < len(self.base_calls) else 'N'
                    if called not in BASES:
                        continue
                    original_signal = self._get_peak_signal(called, center)

                    # Shifted position signal
                    shifted_center = center + size * spacing
                    if 0 <= shifted_center < self.trace_len:
                        # What base would we expect at the shifted position?
                        shifted_idx = j + size if size < 0 else j - size
                        if 0 <= shifted_idx < len(self.base_calls):
                            shifted_base = self.base_calls[shifted_idx]
                            if shifted_base in BASES:
                                shifted_signal = self._get_peak_signal(
                                    shifted_base, shifted_center)
                                score += shifted_signal
                                n_scored += 1

                if n_scored > 0:
                    avg_score = score / n_scored
                    if avg_score > best_score:
                        best_score = avg_score
                        best_size = size

            # Compute confidence from aberrant signal strength
            confidence = min(bp['delta'] * 2, 1.0)

            indel_type = "deletion" if best_size < 0 else "insertion" if best_size > 0 else "unknown"

            results.append({
                'break_pos_0based': pos,
                'break_pos_1based': pos + 1,
                'indel_size': best_size,
                'type': indel_type,
                'aberrant_before': round(bp['before'], 4),
                'aberrant_after': round(bp['after'], 4),
                'aberrant_delta': round(bp['delta'], 4),
                'confidence': round(confidence, 4),
            })

        return results


def subtract_control(sample_traces, control_traces):
    """Subtract matched control trace from sample to enhance variant detection.

    This implements Mode 2 (control-enhanced) of the SDVC algorithm.
    The control trace represents the expected signal for a wild-type sample.
    Subtracting it removes systematic baseline artifacts (dye blobs, baseline
    drift, instrument noise patterns), isolating the variant-specific signal.

    The subtraction is conservative (50% of scaled control) to avoid
    over-subtraction that could create false negative regions.

    Parameters
    ----------
    sample_traces : dict
        Sample trace data {"A": array, "C": array, "G": array, "T": array}.
    control_traces : dict
        Matched control trace data with same structure.

    Returns
    -------
    dict
        Enhanced traces with systematic baseline removed.
    """
    enhanced = {}
    for base in BASES:
        s = sample_traces[base].astype(np.float64)
        c = control_traces[base].astype(np.float64)

        # Handle length mismatch — align to shorter trace
        min_len = min(len(s), len(c))
        s = s[:min_len]
        c = c[:min_len]

        # Robust amplitude scaling: match control to sample's dominant signal
        s_p90 = np.percentile(s[s > 0], 90) if np.any(s > 0) else 1.0
        c_p90 = np.percentile(c[c > 0], 90) if np.any(c > 0) else 1.0
        scale_factor = s_p90 / max(c_p90, 1.0)

        # Conservative subtraction: remove 50% of scaled control baseline
        # This removes systematic artifacts while preserving real signal
        baseline_estimate = 0.5 * scale_factor * c
        enhanced_signal = s - baseline_estimate

        # Clip: ensure non-negative, convert back to int16
        result = np.clip(enhanced_signal, 0, 32767).astype(np.int16)

        # Pad back to original length if needed
        if len(result) < len(sample_traces[base]):
            padded = np.zeros(len(sample_traces[base]), dtype=np.int16)
            padded[:len(result)] = result
            enhanced[base] = padded
        else:
            enhanced[base] = result

    return enhanced


def call_variants_from_traces(traces, peak_positions, base_calls=None,
                              min_threshold=0.05, sensitivity=0.5,
                              prior=0.01, window_size=5):
    """Functional interface to SDVC variant calling.

    Convenience function that creates a VariantCaller and runs it.

    Parameters
    ----------
    traces : dict
        Mapping of base characters to numpy arrays of trace intensities.
    peak_positions : list of int
        Peak center positions in trace coordinates.
    base_calls : str, optional
        Called base sequence.
    min_threshold : float
        Minimum minor allele frequency threshold (default 0.05).
    sensitivity : float
        Dynamic threshold sensitivity (default 0.5).
    prior : float
        Bayesian prior for variant (default 0.01).
    window_size : int
        Multi-position consistency window (default 5).

    Returns
    -------
    list of dict
        All positions with variant calling results.
    """
    caller = VariantCaller(
        traces, peak_positions, base_calls,
        min_threshold=min_threshold, sensitivity=sensitivity,
        prior=prior, window_size=window_size,
    )
    return caller.call_variants()


def write_variants_csv(variants, output_path, sample_name=""):
    """Write variant calling results to CSV file.

    Parameters
    ----------
    variants : list of dict
        Output from VariantCaller.call_variants() or get_variants().
    output_path : str
        Path to CSV output file.
    sample_name : str
        Sample identifier for the CSV.
    """
    import csv
    import os

    fieldnames = [
        "sample", "position", "consensus_base",
        "major_base", "major_freq_%",
        "minor_base", "minor_freq_%",
        "freq_A_%", "freq_C_%", "freq_G_%", "freq_T_%",
        "is_variant", "confidence", "snr", "threshold",
    ]

    write_header = not os.path.exists(output_path) or os.path.getsize(output_path) == 0

    with open(output_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()

        for v in variants:
            writer.writerow({
                "sample": sample_name,
                "position": v["pos_1based"],
                "consensus_base": v["consensus_base"],
                "major_base": v["major_base"],
                "major_freq_%": f"{v['major_freq'] * 100:.1f}",
                "minor_base": v["minor_base"],
                "minor_freq_%": f"{v['minor_freq'] * 100:.1f}",
                "freq_A_%": f"{v['freq_A'] * 100:.1f}",
                "freq_C_%": f"{v['freq_C'] * 100:.1f}",
                "freq_G_%": f"{v['freq_G'] * 100:.1f}",
                "freq_T_%": f"{v['freq_T'] * 100:.1f}",
                "is_variant": v["is_variant"],
                "confidence": f"{v['confidence']:.4f}",
                "snr": f"{v['snr']:.2f}",
                "threshold": f"{v['threshold']:.4f}",
            })

    return output_path


def write_variants_vcf(variants, output_path, sample_name="Sample"):
    """Write variant calling results in simplified VCF-like format.

    Parameters
    ----------
    variants : list of dict
        Output from VariantCaller.get_variants().
    output_path : str
        Path to VCF output file.
    sample_name : str
        Sample name for VCF header.
    """
    with open(output_path, "w") as f:
        # VCF header
        f.write("##fileformat=VCFv4.2\n")
        f.write(f"##source=ab1tools_SDVC\n")
        f.write('##INFO=<ID=AF,Number=1,Type=Float,Description="Minor allele frequency">\n')
        f.write('##INFO=<ID=CONF,Number=1,Type=Float,Description="SDVC confidence score">\n')
        f.write('##INFO=<ID=SNR,Number=1,Type=Float,Description="Local signal-to-noise ratio">\n')
        f.write(f"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n")

        for v in variants:
            if not v["is_variant"]:
                continue
            chrom = sample_name
            pos = v["pos_1based"]
            ref = v["major_base"]
            alt = v["minor_base"]
            # Quality: phred-scaled confidence
            conf = v["confidence"]
            qual = min(99, int(-10 * math.log10(max(1 - conf, 1e-10))))
            filt = "PASS" if conf >= 0.3 else "LowConf"
            info = f"AF={v['minor_freq']:.4f};CONF={conf:.4f};SNR={v['snr']:.2f}"
            f.write(f"{chrom}\t{pos}\t.\t{ref}\t{alt}\t{qual}\t{filt}\t{info}\n")

    return output_path
